title: Sakshi Pandey
logo: /assets/img/sakshiI.jpg
description: Seeking an opportunity where I can apply my technical skills in web development, data analysis, and machine learning, 
while learning and contributing to real-world projects in a professional environment.
show_downloads: false
theme: jekyll-theme-minimal
